#!/usr/bin/env python3

import sys


def binary_search(needle, haystack):
    """
    Perform binary search for needle in haystack.
    Return the index of needle in haystack, or -1 if not found.
    """
    left, right = 0, len(haystack) - 1
    while left <= right:
        mid = (left + right) // 2
        if haystack[mid] < needle:
            left = mid + 1
        elif haystack[mid] > needle:
            right = mid - 1
        else:
            return mid
    return -1


def main():
    """
    Entry point for the script.
    """
    if len(sys.argv) != 3:
        print("Usage: appne <needle> <haystack>")
        sys.exit(1)

    needle = int(sys.argv[1])
    haystack = [int(i) for i in sys.argv[2].strip('[]').split(',')]

    index = binary_search(needle, haystack)

    if index == -1:
        print(f"{needle} not found in {haystack}")
    else:
        print(f"{needle} found at index {index} in {haystack}")


if __name__ == "__main__":
    main()
